version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/php/Dockerfile
    container_name: cake-backend
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: cake-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sweets
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: cake-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

volumes:
  mysql-data:
  node_modules: {}
